import { Heading } from "@/components/ui/Heading";
import { CodeBlock } from "@/components/ui/CodeBlock";
import { Callout } from "@/components/ui/Callout";

export const metadata = {
  title: "Vercel Deploy - BunTok",
  description: "Deploy BunTok to Vercel with Bun runtime.",
};

export default function VercelPage() {
  return (
    <>
      <Heading level={1}>Vercel Deployment</Heading>
      <p className="my-3 text-text-secondary leading-relaxed">
        BunTok supports zero-config deployment on Vercel with Bun runtime. Select &quot;Yes&quot;
        when prompted during <code>buntok init</code> to set up the clean entry point pattern.
      </p>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        How It Works
      </Heading>
      <p className="my-3 text-text-secondary leading-relaxed">
        BunTok uses a single <code>server.ts</code> entry point for all modes — local development
        and Vercel. The <code>app.listen()</code> method auto-detects the runtime: it calls{" "}
        <code>Bun.serve()</code> locally, and works seamlessly on Vercel serverless.
      </p>

      <Heading level={3} className="text-lg font-semibold mt-6 mb-2 text-text-primary">
        server.ts — universal entry point
      </Heading>
      <CodeBlock
        language="typescript"
        code={`import { app } from "./src/index";
import { env } from "./src/env";

app.listen(env.PORT);`}
      />

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Why `app.listen()` Works Everywhere
      </Heading>
      <ul className="my-3 text-text-secondary leading-relaxed list-disc list-inside space-y-1">
        <li>
          <strong>Local dev</strong> — <code>app.listen()</code> calls <code>Bun.serve()</code>{" "}
          and binds to a port
        </li>
        <li>
          <strong>Vercel</strong> — <code>app.listen()</code> detects the serverless environment
          and delegates to <code>app.fetch()</code> automatically
        </li>
        <li>No separate entry points needed — one <code>server.ts</code> works for both</li>
      </ul>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        app.fetch() vs app.listen()
      </Heading>
      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b border-border text-text-secondary">
              <th className="py-2 pr-4">Method</th>
              <th className="py-2 pr-4">Use Case</th>
              <th className="py-2">Binds Port</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-border">
              <td className="py-2 pr-4 font-mono text-xs text-accent">app.listen(port)</td>
              <td className="py-2">Local development</td>
              <td className="py-2">Yes</td>
            </tr>
            <tr className="border-b border-border">
              <td className="py-2 pr-4 font-mono text-xs text-accent">app.fetch(request)</td>
              <td className="py-2">Vercel/serverless</td>
              <td className="py-2">No</td>
            </tr>
            <tr className="border-b border-border">
              <td className="py-2 pr-4 font-mono text-xs text-accent">app.request(input, init?)</td>
              <td className="py-2">Testing</td>
              <td className="py-2">No</td>
            </tr>
          </tbody>
        </table>
      </div>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        vercel.json
      </Heading>
      <p className="my-3 text-text-secondary leading-relaxed">
        Generated by <code>buntok init</code> when Vercel is selected:
      </p>
      <CodeBlock
        language="json"
        code={`{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "framework": "bun",
  "bunVersion": "1.4.x"
}`}
      />
      <ul className="my-3 text-text-secondary leading-relaxed list-disc list-inside space-y-1">
        <li>
          <code>framework: &quot;bun&quot;</code> — tells Vercel to use Bun runtime (required for
          GitHub-triggered deploys).
        </li>
        <li>
          <code>bunVersion: &quot;1.4.x&quot;</code> — pins the Bun runtime version.
        </li>
      </ul>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Deploy
      </Heading>
      <CodeBlock
        language="bash"
        code={`# Install Vercel CLI
npm i -g vercel

# Deploy (preview)
vercel

# Production deploy
vercel --prod`}
      />

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Local Development
      </Heading>
      <CodeBlock language="bash" code={`bun run dev   # runs: bun --watch server.ts`} />
      <p className="my-3 text-text-secondary leading-relaxed">
        The <code>dev</code> script runs <code>server.ts</code> which calls <code>app.listen()</code>{" "}
        — this is separate from the Vercel entry point.
      </p>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Project Structure
      </Heading>
      <CodeBlock
        code={`my-app/
├── src/
│   ├── index.ts              # export const app = new App()
│   ├── env.ts                # App.validateEnv({ PORT, ... })
│   ├── controllers/
│   ├── services/
│   └── repositories/
├── server.ts                 # app.listen(env.PORT) — universal entry point
├── vercel.json               # Vercel config (framework: "bun")
├── package.json
└── ...`}
      />

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Notes
      </Heading>
      <ul className="my-3 text-text-secondary leading-relaxed list-disc list-inside space-y-1">
        <li>WebSocket routes may need additional Vercel configuration</li>
        <li>
          For monorepos, set the <strong>Root Directory</strong> in Vercel dashboard to your
          project subfolder
        </li>
      </ul>

      <Callout type="info">
        <code>app.listen()</code> is the universal entry point — it works for both local
        development and Vercel serverless. No special configuration needed.
      </Callout>
    </>
  );
}
