import { Heading } from "@/components/ui/Heading";
import { CodeBlock } from "@/components/ui/CodeBlock";
import { Callout } from "@/components/ui/Callout";

export const metadata = {
  title: "Vercel Deploy - BunTok",
  description: "Deploy BunTok to Vercel with Bun runtime.",
};

export default function VercelPage() {
  return (
    <>
      <Heading level={1}>Vercel Deployment</Heading>
      <p className="my-3 text-text-secondary leading-relaxed">
        BunTok supports zero-config deployment on Vercel with Bun runtime. Select &quot;Yes&quot;
        when prompted during <code>buntok init</code> to set up the clean entry point pattern.
      </p>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Clean Entry Point Pattern
      </Heading>
      <p className="my-3 text-text-secondary leading-relaxed">
        When Vercel is selected, the project uses a clean entry point pattern (matching Elysia/Hono):{" "}
        <code>src/index.ts</code> exports the app cleanly without calling{" "}
        <code>app.listen()</code>, and a separate <code>server.ts</code> is created for local
        development.
      </p>

      <Heading level={3} className="text-lg font-semibold mt-6 mb-2 text-text-primary">
        src/index.ts — clean export only
      </Heading>
      <CodeBlock
        language="typescript"
        code={`import { App } from "@buntok/core";
import { env } from "./env";

export const app = new App();

// ... register routes, middleware, controllers ...

export default app;`}
      />

      <Heading level={3} className="text-lg font-semibold mt-6 mb-2 text-text-primary">
        server.ts — local development only
      </Heading>
      <CodeBlock
        language="typescript"
        code={`import { app } from "./src/index";
import { env } from "./src/env";

app.listen(env.PORT);`}
      />

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Why Two Files?
      </Heading>
      <ul className="my-3 text-text-secondary leading-relaxed list-disc list-inside space-y-1">
        <li>
          <strong>Vercel</strong> needs <code>export default app</code> — Vercel&apos;s Bun runtime
          calls <code>app.fetch()</code> automatically
        </li>
        <li>
          <strong>Local dev</strong> needs <code>app.listen()</code> — binds to a port for{" "}
          <code>bun run dev</code>
        </li>
        <li>Separating them keeps src/index.ts clean and Vercel-compatible</li>
      </ul>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        app.fetch() vs app.listen()
      </Heading>
      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead>
            <tr className="border-b border-border text-text-secondary">
              <th className="py-2 pr-4">Method</th>
              <th className="py-2 pr-4">Use Case</th>
              <th className="py-2">Binds Port</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-border">
              <td className="py-2 pr-4 font-mono text-xs text-accent">app.listen(port)</td>
              <td className="py-2">Local development</td>
              <td className="py-2">Yes</td>
            </tr>
            <tr className="border-b border-border">
              <td className="py-2 pr-4 font-mono text-xs text-accent">app.fetch(request)</td>
              <td className="py-2">Vercel/serverless</td>
              <td className="py-2">No</td>
            </tr>
            <tr className="border-b border-border">
              <td className="py-2 pr-4 font-mono text-xs text-accent">app.request(input, init?)</td>
              <td className="py-2">Testing</td>
              <td className="py-2">No</td>
            </tr>
          </tbody>
        </table>
      </div>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        vercel.json
      </Heading>
      <p className="my-3 text-text-secondary leading-relaxed">
        Generated by <code>buntok init</code> when Vercel is selected:
      </p>
      <CodeBlock
        language="json"
        code={`{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "bunVersion": "1.4.x",
  "buildCommand": null
}`}
      />
      <ul className="my-3 text-text-secondary leading-relaxed list-disc list-inside space-y-1">
        <li>
          <code>buildCommand: null</code> — overrides package.json build script. Vercel skips build
          and transpiles TS on-the-fly.
        </li>
        <li>
          <code>bunVersion: &quot;1.4.x&quot;</code> — pins the Bun runtime version.
        </li>
      </ul>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Deploy
      </Heading>
      <CodeBlock
        language="bash"
        code={`# Install Vercel CLI
npm i -g vercel

# Deploy (preview)
vercel

# Production deploy
vercel --prod`}
      />

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Local Development
      </Heading>
      <CodeBlock language="bash" code={`bun run dev   # runs: bun --watch server.ts`} />
      <p className="my-3 text-text-secondary leading-relaxed">
        The <code>dev</code> script runs <code>server.ts</code> which calls <code>app.listen()</code>{" "}
        — this is separate from the Vercel entry point.
      </p>

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Project Structure
      </Heading>
      <CodeBlock
        code={`my-app/
├── src/
│   ├── index.ts              # export default app (clean — no listen)
│   ├── env.ts                # App.validateEnv({ PORT, AUTH_STORE, ... })
│   ├── controllers/
│   ├── services/
│   └── repositories/
├── server.ts                 # app.listen(env.PORT) — local dev only
├── vercel.json               # Vercel config
├── package.json              # dev script: bun --watch server.ts
└── ...`}
      />

      <Heading level={2} className="text-xl font-semibold mt-8 mb-3 text-text-primary">
        Limitations
      </Heading>
      <ul className="my-3 text-text-secondary leading-relaxed list-disc list-inside space-y-1">
        <li>
          <code>app.listen()</code> in src/index.ts will NOT work on Vercel (Vercel doesn&apos;t
          call listen)
        </li>
        <li>
          server.ts is NOT deployed to Vercel — only src/index.ts is used
        </li>
        <li>WebSocket routes may need additional Vercel configuration</li>
      </ul>

      <Callout type="info">
        When Vercel is selected, <code>src/index.ts</code> does NOT contain{" "}
        <code>app.listen()</code>. The <code>server.ts</code> file is only used for local
        development via <code>bun run dev</code>.
      </Callout>
    </>
  );
}
